
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov 22 2024 19:33:47 IST (Nov 22 2024 14:03:47 UTC)

// Verification Directory fv/ATM 

module ATM(clk, reset, pin_input, amount_input,
     biometric_authenticated, change_pin_request, new_pin,
     inactivity_timeout, transaction_success, transaction_error,
     pin_change_success, account_locked, timeout_error);
  input clk, reset, biometric_authenticated, change_pin_request,
       inactivity_timeout;
  input [3:0] pin_input, new_pin;
  input [7:0] amount_input;
  output transaction_success, transaction_error, pin_change_success,
       account_locked, timeout_error;
  wire clk, reset, biometric_authenticated, change_pin_request,
       inactivity_timeout;
  wire [3:0] pin_input, new_pin;
  wire [7:0] amount_input;
  wire transaction_success, transaction_error, pin_change_success,
       account_locked, timeout_error;
  wire [3:0] login_attempts;
  wire [3:0] current_pin;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_46, n_47, n_48, n_49, n_71, n_72;
  DFFRHQX1 transaction_success_reg(.RN (n_49), .CK (clk), .D (n_48), .Q
       (transaction_success));
  DFFRHQX1 \login_attempts_reg[3] (.RN (n_49), .CK (clk), .D (n_46), .Q
       (login_attempts[3]));
  DFFRHQX1 pin_change_success_reg(.RN (n_49), .CK (clk), .D (n_71), .Q
       (pin_change_success));
  NOR2XL g1629__2398(.A (account_locked), .B (n_44), .Y (n_48));
  DFFRHQX1 transaction_error_reg(.RN (n_49), .CK (clk), .D (n_42), .Q
       (transaction_error));
  SDFFSHQX1 \current_pin_reg[1] (.SN (n_49), .CK (clk), .D
       (current_pin[1]), .SI (new_pin[1]), .SE (n_47), .Q
       (current_pin[1]));
  SDFFSHQX1 \current_pin_reg[3] (.SN (n_49), .CK (clk), .D
       (current_pin[3]), .SI (new_pin[3]), .SE (n_47), .Q
       (current_pin[3]));
  OAI31XL g1639__5107(.A0 (login_attempts[3]), .A1 (n_40), .A2 (n_39),
       .B0 (n_43), .Y (n_46));
  SDFFRHQX1 \current_pin_reg[0] (.RN (n_49), .CK (clk), .D
       (current_pin[0]), .SI (new_pin[0]), .SE (n_47), .Q
       (current_pin[0]));
  SDFFRHQX1 \current_pin_reg[2] (.RN (n_49), .CK (clk), .D
       (current_pin[2]), .SI (new_pin[2]), .SE (n_47), .Q
       (current_pin[2]));
  MXI2XL g1631__4319(.A (n_36), .B (transaction_success), .S0 (n_19),
       .Y (n_44));
  NAND2XL g1645__8428(.A (login_attempts[3]), .B (n_32), .Y (n_43));
  NOR2XL g1633__5526(.A (n_47), .B (n_34), .Y (n_42));
  DFFRHQX1 \login_attempts_reg[1] (.RN (n_49), .CK (clk), .D (n_29), .Q
       (login_attempts[1]));
  OAI22XL g1647__6783(.A0 (n_40), .A1 (n_72), .B0 (login_attempts[2]),
       .B1 (n_39), .Y (n_41));
  OAI211XL g1646__3680(.A0 (n_28), .A1 (n_3), .B0 (n_0), .C0 (n_39), .Y
       (n_37));
  NOR3X1 g1638__1617(.A (inactivity_timeout), .B (n_31), .C (n_33), .Y
       (n_36));
  AOI31X1 g1658__2802(.A0 (n_11), .A1 (n_12), .A2 (n_16), .B0 (n_35),
       .Y (n_47));
  NOR3X1 g1640__1705(.A (change_pin_request), .B (n_26), .C (n_33), .Y
       (n_34));
  OAI2BB1XL g1648__5122(.A0N (n_40), .A1N (n_31), .B0 (n_72), .Y
       (n_32));
  OAI31XL g1651__8246(.A0 (login_attempts[1]), .A1 (n_24), .A2 (n_28),
       .B0 (n_27), .Y (n_29));
  NAND2XL g1653__7098(.A (login_attempts[1]), .B (n_23), .Y (n_27));
  NAND2BX1 g1660__6131(.AN (n_26), .B (change_pin_request), .Y (n_35));
  MXI2XL g1656__1881(.A (n_22), .B (n_28), .S0 (n_24), .Y (n_25));
  NAND4BXL g1652__7482(.AN (amount_input[7]), .B
       (biometric_authenticated), .C (n_17), .D (n_18), .Y (n_33));
  NAND3BX1 g1657__4733(.AN (n_28), .B (login_attempts[0]), .C
       (login_attempts[1]), .Y (n_39));
  OAI2BB1X1 g1662__6161(.A0N (n_24), .A1N (n_31), .B0 (n_22), .Y
       (n_23));
  NAND2XL g1663__9315(.A (n_22), .B (n_20), .Y (n_26));
  NOR3BX1 g1666__2883(.AN (change_pin_request), .B
       (inactivity_timeout), .C (n_31), .Y (n_19));
  NAND2XL g1664__2346(.A (n_22), .B (n_31), .Y (n_28));
  OR4X1 g1661__1666(.A (amount_input[2]), .B (amount_input[3]), .C
       (amount_input[4]), .D (n_14), .Y (n_18));
  CLKINVX1 g1668(.A (n_31), .Y (n_20));
  NAND3BXL g1659__7410(.AN (n_15), .B (amount_input[6]), .C
       (amount_input[5]), .Y (n_17));
  AOI221X1 g1672__6417(.A0 (n_8), .A1 (new_pin[3]), .B0 (n_9), .B1
       (new_pin[1]), .C0 (n_10), .Y (n_16));
  NAND4XL g1669__5477(.A (n_5), .B (n_6), .C (n_7), .D (n_4), .Y
       (n_31));
  AOI211X1 g1667__2398(.A0 (amount_input[2]), .A1 (n_13), .B0
       (amount_input[3]), .C0 (amount_input[4]), .Y (n_15));
  OR3XL g1671__5107(.A (amount_input[5]), .B (amount_input[6]), .C
       (n_13), .Y (n_14));
  OAI21XL g1673__6260(.A0 (current_pin[0]), .A1 (new_pin[0]), .B0
       (n_2), .Y (n_12));
  OAI21XL g1674__4319(.A0 (current_pin[2]), .A1 (new_pin[2]), .B0
       (n_1), .Y (n_11));
  SDFFRHQX1 timeout_error_reg(.RN (n_49), .CK (clk), .D
       (inactivity_timeout), .SI (timeout_error), .SE (account_locked),
       .Q (timeout_error));
  OAI22X1 g1675__8428(.A0 (n_9), .A1 (new_pin[1]), .B0 (n_8), .B1
       (new_pin[3]), .Y (n_10));
  MXI2XL g1676__5526(.A (current_pin[3]), .B (n_8), .S0 (pin_input[3]),
       .Y (n_7));
  MXI2XL g1677__6783(.A (current_pin[1]), .B (n_9), .S0 (pin_input[1]),
       .Y (n_6));
  XNOR2XL g1678__3680(.A (current_pin[2]), .B (pin_input[2]), .Y (n_5));
  XNOR2XL g1679__1617(.A (current_pin[0]), .B (pin_input[0]), .Y (n_4));
  NOR2XL g1684__2802(.A (login_attempts[3]), .B (login_attempts[2]), .Y
       (n_3));
  OR2XL g1680__1705(.A (amount_input[1]), .B (amount_input[0]), .Y
       (n_13));
  NAND2XL g1682__5122(.A (current_pin[0]), .B (new_pin[0]), .Y (n_2));
  NAND2XL g1683__8246(.A (current_pin[2]), .B (new_pin[2]), .Y (n_1));
  NOR2XL g1681__7098(.A (inactivity_timeout), .B (account_locked), .Y
       (n_22));
  CLKINVX1 g1685(.A (current_pin[3]), .Y (n_8));
  CLKINVX1 g1687(.A (current_pin[1]), .Y (n_9));
  INVXL g1690(.A (reset), .Y (n_49));
  DFFRX1 account_locked_reg(.RN (n_49), .CK (clk), .D (n_37), .Q
       (account_locked), .QN (n_0));
  DFFRX1 \login_attempts_reg[0] (.RN (n_49), .CK (clk), .D (n_25), .Q
       (login_attempts[0]), .QN (n_24));
  DFFRX1 \login_attempts_reg[2] (.RN (n_49), .CK (clk), .D (n_41), .Q
       (login_attempts[2]), .QN (n_40));
  AO21X1 g2(.A0 (pin_change_success), .A1 (n_35), .B0 (n_47), .Y
       (n_71));
  AOI2BB1XL g1710(.A0N (login_attempts[1]), .A1N (n_20), .B0 (n_23), .Y
       (n_72));
endmodule

