
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov 22 2024 19:31:24 IST (Nov 22 2024 14:01:24 UTC)

// Verification Directory fv/ATM 

module ATM(clk, reset, pin_input, amount_input,
     biometric_authenticated, change_pin_request, new_pin,
     inactivity_timeout, transaction_success, transaction_error,
     pin_change_success, account_locked, timeout_error, SE, scan_in,
     scan_out);
  input clk, reset, biometric_authenticated, change_pin_request,
       inactivity_timeout, SE, scan_in;
  input [3:0] pin_input, new_pin;
  input [7:0] amount_input;
  output transaction_success, transaction_error, pin_change_success,
       account_locked, timeout_error, scan_out;
  wire clk, reset, biometric_authenticated, change_pin_request,
       inactivity_timeout, SE, scan_in;
  wire [3:0] pin_input, new_pin;
  wire [7:0] amount_input;
  wire transaction_success, transaction_error, pin_change_success,
       account_locked, timeout_error, scan_out;
  wire [3:0] login_attempts;
  wire [3:0] current_pin;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_43, n_44, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_76, n_77;
  assign scan_out = transaction_success;
  SDFFRHQX1 transaction_success_reg(.RN (n_54), .CK (clk), .D (n_53),
       .SI (transaction_error), .SE (SE), .Q (transaction_success));
  SDFFRHQX1 \login_attempts_reg[3] (.RN (n_54), .CK (clk), .D (n_52),
       .SI (login_attempts[2]), .SE (SE), .Q (login_attempts[3]));
  SDFFSHQX1 \current_pin_reg[3] (.SN (n_54), .CK (clk), .D (n_48), .SI
       (current_pin[2]), .SE (SE), .Q (current_pin[3]));
  SDFFRHQX1 \current_pin_reg[0] (.RN (n_54), .CK (clk), .D (n_47), .SI
       (account_locked), .SE (SE), .Q (current_pin[0]));
  SDFFRHQX1 pin_change_success_reg(.RN (n_54), .CK (clk), .D (n_76),
       .SI (login_attempts[3]), .SE (SE), .Q (pin_change_success));
  SDFFSHQX1 \current_pin_reg[1] (.SN (n_54), .CK (clk), .D (n_50), .SI
       (current_pin[0]), .SE (SE), .Q (current_pin[1]));
  SDFFRHQX1 \current_pin_reg[2] (.RN (n_54), .CK (clk), .D (n_51), .SI
       (current_pin[1]), .SE (SE), .Q (current_pin[2]));
  SDFFRHQX1 transaction_error_reg(.RN (n_54), .CK (clk), .D (n_44), .SI
       (timeout_error), .SE (SE), .Q (transaction_error));
  SDFFRHQX1 \login_attempts_reg[2] (.RN (n_54), .CK (clk), .D (n_41),
       .SI (login_attempts[1]), .SE (SE), .Q (login_attempts[2]));
  NOR2XL g1629__2398(.A (account_locked), .B (n_46), .Y (n_53));
  OAI31X1 g1639__5107(.A0 (login_attempts[3]), .A1 (n_40), .A2 (n_39),
       .B0 (n_43), .Y (n_52));
  SDFFRHQX1 \login_attempts_reg[1] (.RN (n_54), .CK (clk), .D (n_30),
       .SI (login_attempts[0]), .SE (SE), .Q (login_attempts[1]));
  SDFFRHQX1 account_locked_reg(.RN (n_54), .CK (clk), .D (n_38), .SI
       (scan_in), .SE (SE), .Q (account_locked));
  MX2X1 g1647__6260(.A (current_pin[2]), .B (new_pin[2]), .S0 (n_49),
       .Y (n_51));
  MX2X1 g1648__4319(.A (current_pin[1]), .B (new_pin[1]), .S0 (n_49),
       .Y (n_50));
  MX2X1 g1650__8428(.A (current_pin[3]), .B (new_pin[3]), .S0 (n_49),
       .Y (n_48));
  MX2X1 g1651__5526(.A (current_pin[0]), .B (new_pin[0]), .S0 (n_49),
       .Y (n_47));
  MXI2XL g1631__6783(.A (n_37), .B (transaction_success), .S0 (n_20),
       .Y (n_46));
  NOR2XL g1633__1617(.A (n_49), .B (n_35), .Y (n_44));
  NAND2XL g1643__2802(.A (login_attempts[3]), .B (n_33), .Y (n_43));
  SDFFRHQX1 \login_attempts_reg[0] (.RN (n_54), .CK (clk), .D (n_26),
       .SI (current_pin[3]), .SE (SE), .Q (login_attempts[0]));
  OAI22X1 g1649__1705(.A0 (n_40), .A1 (n_77), .B0 (login_attempts[2]),
       .B1 (n_39), .Y (n_41));
  OAI211X1 g1644__5122(.A0 (n_2), .A1 (n_29), .B0 (n_0), .C0 (n_39), .Y
       (n_38));
  NOR3X1 g1638__8246(.A (inactivity_timeout), .B (n_32), .C (n_34), .Y
       (n_37));
  AOI31X1 g1662__7098(.A0 (n_10), .A1 (n_9), .A2 (n_17), .B0 (n_36), .Y
       (n_49));
  NOR3X1 g1640__6131(.A (change_pin_request), .B (n_24), .C (n_34), .Y
       (n_35));
  OAI2BB1XL g1652__1881(.A0N (n_40), .A1N (n_32), .B0 (n_77), .Y
       (n_33));
  OAI31X1 g1655__5115(.A0 (login_attempts[1]), .A1 (n_25), .A2 (n_29),
       .B0 (n_28), .Y (n_30));
  NAND2XL g1657__7482(.A (login_attempts[1]), .B (n_27), .Y (n_28));
  OAI22X1 g1660__6161(.A0 (login_attempts[0]), .A1 (n_29), .B0 (n_25),
       .B1 (n_23), .Y (n_26));
  NAND2BX1 g1664__9315(.AN (n_24), .B (change_pin_request), .Y (n_36));
  NAND4BXL g1656__9945(.AN (amount_input[7]), .B
       (biometric_authenticated), .C (n_18), .D (n_19), .Y (n_34));
  NAND3BX1 g1661__2883(.AN (n_29), .B (login_attempts[0]), .C
       (login_attempts[1]), .Y (n_39));
  OAI2BB1X1 g1666__2346(.A0N (n_25), .A1N (n_32), .B0 (n_23), .Y
       (n_27));
  NAND2XL g1667__1666(.A (n_23), .B (n_21), .Y (n_24));
  NOR3BX1 g1670__6417(.AN (change_pin_request), .B
       (inactivity_timeout), .C (n_32), .Y (n_20));
  NAND2XL g1668__5477(.A (n_23), .B (n_32), .Y (n_29));
  OR4X1 g1665__2398(.A (amount_input[2]), .B (amount_input[3]), .C
       (amount_input[4]), .D (n_15), .Y (n_19));
  CLKINVX1 g1672(.A (n_32), .Y (n_21));
  NAND3BXL g1663__5107(.AN (n_16), .B (amount_input[6]), .C
       (amount_input[5]), .Y (n_18));
  SDFFRHQX1 timeout_error_reg(.RN (n_54), .CK (clk), .D (n_6), .SI
       (pin_change_success), .SE (SE), .Q (timeout_error));
  AOI221X1 g1676__6260(.A0 (n_11), .A1 (new_pin[3]), .B0 (n_12), .B1
       (new_pin[1]), .C0 (n_13), .Y (n_17));
  OR4X1 g1673__4319(.A (n_4), .B (n_8), .C (n_7), .D (n_5), .Y (n_32));
  AOI211X1 g1671__8428(.A0 (amount_input[2]), .A1 (n_14), .B0
       (amount_input[3]), .C0 (amount_input[4]), .Y (n_16));
  OR3XL g1675__5526(.A (amount_input[5]), .B (amount_input[6]), .C
       (n_14), .Y (n_15));
  OAI22X1 g1677__6783(.A0 (n_12), .A1 (new_pin[1]), .B0 (n_11), .B1
       (new_pin[3]), .Y (n_13));
  OAI21XL g1678__3680(.A0 (current_pin[2]), .A1 (new_pin[2]), .B0
       (n_1), .Y (n_10));
  OAI21XL g1679__1617(.A0 (current_pin[0]), .A1 (new_pin[0]), .B0
       (n_3), .Y (n_9));
  MXI2XL g1682__2802(.A (n_11), .B (current_pin[3]), .S0
       (pin_input[3]), .Y (n_8));
  MXI2XL g1683__1705(.A (n_12), .B (current_pin[1]), .S0
       (pin_input[1]), .Y (n_7));
  MX2X1 g1684__5122(.A (inactivity_timeout), .B (timeout_error), .S0
       (account_locked), .Y (n_6));
  XOR2XL g1680__8246(.A (current_pin[2]), .B (pin_input[2]), .Y (n_5));
  XOR2XL g1681__7098(.A (current_pin[0]), .B (pin_input[0]), .Y (n_4));
  OR2XL g1685__6131(.A (amount_input[1]), .B (amount_input[0]), .Y
       (n_14));
  NOR2XL g1686__1881(.A (inactivity_timeout), .B (account_locked), .Y
       (n_23));
  NAND2XL g1687__5115(.A (current_pin[0]), .B (new_pin[0]), .Y (n_3));
  NOR2XL g1689__7482(.A (login_attempts[3]), .B (login_attempts[2]), .Y
       (n_2));
  NAND2XL g1688__4733(.A (current_pin[2]), .B (new_pin[2]), .Y (n_1));
  CLKINVX1 g1692(.A (current_pin[1]), .Y (n_12));
  CLKINVX1 g1690(.A (login_attempts[0]), .Y (n_25));
  INVXL g1695(.A (reset), .Y (n_54));
  INVXL g1691(.A (account_locked), .Y (n_0));
  CLKINVX1 g1693(.A (current_pin[3]), .Y (n_11));
  CLKINVX1 g1694(.A (login_attempts[2]), .Y (n_40));
  AO21X1 g2(.A0 (pin_change_success), .A1 (n_36), .B0 (n_49), .Y
       (n_76));
  AOI2BB1X1 g1709(.A0N (login_attempts[1]), .A1N (n_21), .B0 (n_27), .Y
       (n_77));
endmodule

